spring.application.name=developer-portfolio
server.port=8081
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio
spring.datasource.username=root
spring.datasource.password=Ansari@123
